server:
  port: 9092
  
spring:
 datasource:
   url: jdbc:mysql://localhost:3306/udemy-db
   
   username: root
   password: root
   
 jpa:
    hibernate:
      ddl-auto: update
      
eureka:
 instance:
   prefer-ip-address: true
   
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka
     
   fetch-registry: true
   register-with-eureka: true